blank_issues_enabled: true
contact_links:
  - name: Questions & ideas
    url: https://github.com/avytheone/efmesh/discussions
    about: Not sure it's a bug? Want to discuss an approach? Start a discussion.
